CONTACT-FORM
citec-47/PORTFOILIO-WEEK-TWO pull request #1
Opened 2023-01-24 18:04 UTC by citec-47

2023-01-24 19:55 UTC, vickymarz requested changes
Hi @citec-47, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- The README is well documented ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️
_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-24 19:55 UTC, vickymarz commented on index.html
> + <form action="https://formspree.io/f/meqwogjz" method="post">
- [ ] our contact section seems to have a horizontal scroll bar and spaces at the right of the page which is not a good user experience. Kindly fix it 👍🏽 

![image](https://user-images.githubusercontent.com/63473584/214395190-faf43fa8-040d-4e38-980e-bd3cf4790cc7.png)

2023-01-25 06:18 UTC, citec-47 commented
##CHANGES DONE✔✔
#Adjustment of icon pictures✔
#Removal of the horizontal scroll✔

2023-01-25 06:34 UTC, Shedrack-Sunday approved these changes
Hi @citec-47       👋 
 
 # STATUS: APPROVED ✔️  🍾  🥳

 Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉

 ![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)
 
 ## Highlights
✔️  Proper use of Github features 💯 
✔️  well-crafted pull request 👍 
✔️ Linters are passing 👏 
 
 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._
 
- [ ] I made a suggestion concerning the design of your `submit` button and footer social links, which I strongly suggest that you take into consideration. Please find a more detailed review of the comments below

 Cheers and Happy coding!👏👏👏
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-25 06:34 UTC, Shedrack-Sunday commented on index.html
> + </footer>
- [Optional ] Firstly, I must commend you for making the needed changes by the previous reviewer, However, there's a slight variation on your `button`(added border) and social links which do not tally with the Figma design. the idea behind making you stick to such designs is to build a skilled muscle in meeting future project requirements or clients' projects. I've attached a comparison view fro Figma and your design for your assessment. Good job 👏 

# Figma:
![image](https://user-images.githubusercontent.com/50990925/214495872-1ca3d656-8235-43cb-af98-2a788995c3c7.png)

# Your Design:
![image](https://user-images.githubusercontent.com/50990925/214496074-81797320-2681-4cf1-8abf-fa16f26cab77.png)

2023-01-25 06:41 UTC, merged